Repository wecode-bootcamp-korea/17-2nd-shockX-backend, pull requests merged in 2021-03, with the labels that each got.

#1 [17기 송빈호] models.py 생성 완료
  order/__init__.py
  order/admin.py
  order/apps.py
  order/migrations/0001_initial.py
  order/migrations/__init__.py
  order/models.py
  order/tests.py
  order/views.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/views.py
  pull_request_template.md
  shockx/settings.py
  shockx/urls.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20210303_2153.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/views.py
Labels: Status: Accepted

#3 [17기 송빈호] order models.py 수정
  order/models.py
Labels: Status: Accepted

#4 [17기 송빈호] order/models.py 필요없는 class 제거
  order/migrations/0001_initial.py
  order/models.py
  product/migrations/0001_initial.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20210303_2153.py
Labels: Status: 리뷰 요청

#6 [17기 조수아] user, order app models.py 수정
  order/migrations/0001_initial.py
  order/models.py
  product/migrations/0001_initial.py
  user/migrations/0001_initial.py
  user/models.py
Labels: Status: Accepted

#5 [17기 조혜윤]ProductDetailView UnitTest작성완료⭐️
  order/migrations/0001_initial.py
  order/migrations/__init__.py
  order/models.py
  product/migrations/0001_initial.py
  product/migrations/__init__.py
  product/tests.py
  product/urls.py
  product/views.py
  shockx/settings.py
  shockx/urls.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
Labels: Status: 리뷰 요청

#8 [17기 김하성] ADDED unit tests for ProductListView, changed ORDER_STATUS_CHECK to ORDER_STATUS_CURRENT
  product/tests.py
  product/urls.py
  product/views.py
Labels: Status: Accepted

#7 [17기 조수아] buyview GET & POST 작성
  order/models.py
  order/tests.py
  order/urls.py
  order/views.py
  shockx/urls.py
Labels: Status: Accepted

#12 [17기 조수아] PortfolioView 작성
  order/migrations/0001_initial.py
  order/migrations/__init__.py
  order/tests.py
  product/migrations/0001_initial.py
  product/migrations/__init__.py
  shockx/settings.py
  shockx/urls.py
  user/migrations/0001_initial.py
  user/migrations/0002_portfolio.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status: Accepted

#9 [17기 송빈호] kakao sociallogin 구현 완료
  shockx/urls.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status: 리뷰 요청

#10 [17기 송빈호] order sell view 완료
  order/migrations/0001_initial.py
  order/models.py
  order/tests.py
  order/urls.py
  order/views.py
  product/migrations/0001_initial.py
  user/migrations/0001_initial.py
  user/migrations/0002_portfolio.py
  utils.py
Labels: Status: 리뷰 진행중

#11 [17기 김하성] removed detail from product/urls.py, fixed conflicts
  product/tests.py
  product/urls.py
  product/views.py
Labels: Status: 리뷰 요청

#13 [17기 조수아] BuyStatusView, SellStatusView 작성, Unittest 완료
  order/tests.py
  order/urls.py
  order/views.py
Labels: Status: 리뷰 요청

#14 [17기 송빈호] 프론트 요청으로 인한 수정
  order/migrations/0001_initial.py
  order/tests.py
  order/views.py
  product/migrations/0001_initial.py
  user/migrations/0001_initial.py
  user/models.py
  user/views.py
Labels: Status: Accepted

#15 [17기 조수아] order views.py import 수정
  order/tests.py
  order/views.py
  product/tests.py
  user/migrations/0002_auto_20210311_1627.py
  user/models.py
  user/tests.py
  utils.py
Labels: Status: Accepted

#16 [17기 조혜윤] productlist 키,값 추가 , userview 토큰 email로 변경
  product/views.py
  user/views.py
Labels: Status: Accepted

#17 [17기 조수아] buyview, sellview 수정
  order/views.py
Labels: Status: Accepted
